services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
      - 8080:8080
    volumes:
      - ./playwright/neo-test-project:/ivy/data/workspaces/Developer/neo-test-project/neo-test-project/
    user: root
