packages:
  - webviews/process-editor
  - playwright

ignoredBuiltDependencies:
  - esbuild

patchedDependencies:
  monaco-editor: patches/monaco-editor.patch

preferWorkspacePackages: true

publicHoistPattern:
  - eslint

sideEffectsCache: false
