packages:
  - webviews/process-editor
  - playwright

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - monaco-languageclient

preferWorkspacePackages: true

publicHoistPattern:
  - eslint
  - '@codingame/monaco-vscode-*'

overrides:
  'vscode': 'npm:@codingame/monaco-vscode-extension-api@25.1.2'
  'monaco-editor': 'npm:@codingame/monaco-vscode-editor-api@25.1.2'

sideEffectsCache: false
