packages:
  - webviews/process-editor
  - playwright

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - monaco-languageclient

preferWorkspacePackages: true

publicHoistPattern:
  - eslint

sideEffectsCache: false
